services:
  simkes:
    container_name: simkes-api
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - simkes:/usr/src/app
    networks:
      pg:
    restart: always

volumes:
  simkes:

networks:
  pg:
    external: true
